version: "3.1"

services:
  # sqldb:
  #   image: mysql
  #   container_name: fundamental_mysql
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_DATABASE: fundamental_mysql
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin_password
  #     MYSQL_ROOT_PASSWORD: admin_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: always

  # sqlhelper:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - sqldb
  #   ports:
  #     - 8080:8080
  db:
    image: postgres
    container_name: reservation_database
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  db_helper:
    image: dpage/pgadmin4
    container_name: fundamental_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

  reservation-api:
    build: .
    ports:
      - "7777:8000"
    environment:
      - SECRET_KEY=test
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=reservation
      - DB_USERNAME=admin
      - DB_PASSWORD=admin_password
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  mysql_data:
